apiVersion: v1
kind: Service
metadata:
  name: django-app-service
  namespace: django-app
spec:
  type: NodePort
  selector:
    app: django-app
  ports:
    - port: 80
      targetPort: 8000
      nodePort: 30007
